
package ws_cliente_imagenes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImgFuncionalidades", targetNamespace = "http://imagenes/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImgFuncionalidades {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "subirImg", targetNamespace = "http://imagenes/", className = "ws_cliente_imagenes.SubirImg")
    @ResponseWrapper(localName = "subirImgResponse", targetNamespace = "http://imagenes/", className = "ws_cliente_imagenes.SubirImgResponse")
    @Action(input = "http://imagenes/ImgFuncionalidades/subirImgRequest", output = "http://imagenes/ImgFuncionalidades/subirImgResponse")
    public void subirImg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "descargarImg", targetNamespace = "http://imagenes/", className = "ws_cliente_imagenes.DescargarImg")
    @ResponseWrapper(localName = "descargarImgResponse", targetNamespace = "http://imagenes/", className = "ws_cliente_imagenes.DescargarImgResponse")
    @Action(input = "http://imagenes/ImgFuncionalidades/descargarImgRequest", output = "http://imagenes/ImgFuncionalidades/descargarImgResponse")
    public byte[] descargarImg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
