
package ws_cliente_imagenes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImgFuncionalidadesService", targetNamespace = "http://imagenes/", wsdlLocation = "http://localhost:8080/servidor/img?wsdl")
public class ImgFuncionalidadesService
    extends Service
{

    private final static URL IMGFUNCIONALIDADESSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMGFUNCIONALIDADESSERVICE_EXCEPTION;
    private final static QName IMGFUNCIONALIDADESSERVICE_QNAME = new QName("http://imagenes/", "ImgFuncionalidadesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servidor/img?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMGFUNCIONALIDADESSERVICE_WSDL_LOCATION = url;
        IMGFUNCIONALIDADESSERVICE_EXCEPTION = e;
    }

    public ImgFuncionalidadesService() {
        super(__getWsdlLocation(), IMGFUNCIONALIDADESSERVICE_QNAME);
    }

    public ImgFuncionalidadesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMGFUNCIONALIDADESSERVICE_QNAME, features);
    }

    public ImgFuncionalidadesService(URL wsdlLocation) {
        super(wsdlLocation, IMGFUNCIONALIDADESSERVICE_QNAME);
    }

    public ImgFuncionalidadesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMGFUNCIONALIDADESSERVICE_QNAME, features);
    }

    public ImgFuncionalidadesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImgFuncionalidadesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImgFuncionalidades
     */
    @WebEndpoint(name = "ImgFuncionalidadesPort")
    public ImgFuncionalidades getImgFuncionalidadesPort() {
        return super.getPort(new QName("http://imagenes/", "ImgFuncionalidadesPort"), ImgFuncionalidades.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImgFuncionalidades
     */
    @WebEndpoint(name = "ImgFuncionalidadesPort")
    public ImgFuncionalidades getImgFuncionalidadesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imagenes/", "ImgFuncionalidadesPort"), ImgFuncionalidades.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMGFUNCIONALIDADESSERVICE_EXCEPTION!= null) {
            throw IMGFUNCIONALIDADESSERVICE_EXCEPTION;
        }
        return IMGFUNCIONALIDADESSERVICE_WSDL_LOCATION;
    }

}
