
package latam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Brasil", targetNamespace = "http://mio/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Brasil {


    /**
     * 
     * @param nombreDeLaVariableQueApareceEnWsdl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://mio/Brasil/rioRequest", output = "http://mio/Brasil/rioResponse")
    public String rio(
        @WebParam(name = "Nombre_de_la_variable_que_aparece_en_wsdl", partName = "Nombre_de_la_variable_que_aparece_en_wsdl")
        String nombreDeLaVariableQueApareceEnWsdl);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "san_pablo")
    @WebResult(partName = "return")
    @Action(input = "http://mio/Brasil/san_pabloRequest", output = "http://mio/Brasil/san_pabloResponse")
    public String sanPablo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
