
package latam;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BrasilService", targetNamespace = "http://mio/", wsdlLocation = "http://localhost:8080/servidor/latam/brasil?wsdl")
public class BrasilService
    extends Service
{

    private final static URL BRASILSERVICE_WSDL_LOCATION;
    private final static WebServiceException BRASILSERVICE_EXCEPTION;
    private final static QName BRASILSERVICE_QNAME = new QName("http://mio/", "BrasilService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servidor/latam/brasil?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BRASILSERVICE_WSDL_LOCATION = url;
        BRASILSERVICE_EXCEPTION = e;
    }

    public BrasilService() {
        super(__getWsdlLocation(), BRASILSERVICE_QNAME);
    }

    public BrasilService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BRASILSERVICE_QNAME, features);
    }

    public BrasilService(URL wsdlLocation) {
        super(wsdlLocation, BRASILSERVICE_QNAME);
    }

    public BrasilService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BRASILSERVICE_QNAME, features);
    }

    public BrasilService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrasilService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Brasil
     */
    @WebEndpoint(name = "BrasilPort")
    public Brasil getBrasilPort() {
        return super.getPort(new QName("http://mio/", "BrasilPort"), Brasil.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Brasil
     */
    @WebEndpoint(name = "BrasilPort")
    public Brasil getBrasilPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mio/", "BrasilPort"), Brasil.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BRASILSERVICE_EXCEPTION!= null) {
            throw BRASILSERVICE_EXCEPTION;
        }
        return BRASILSERVICE_WSDL_LOCATION;
    }

}
