
package latam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Uruguay", targetNamespace = "http://mio/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Uruguay {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://mio/Uruguay/montevideoRequest", output = "http://mio/Uruguay/montevideoResponse")
    public String montevideo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://mio/Uruguay/canelonesRequest", output = "http://mio/Uruguay/canelonesResponse")
    public String canelones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
