
package francia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FranciaService", targetNamespace = "http://codejava.net/", wsdlLocation = "http://localhost:8080/servidor/europa/francia?wsdl")
public class FranciaService
    extends Service
{

    private final static URL FRANCIASERVICE_WSDL_LOCATION;
    private final static WebServiceException FRANCIASERVICE_EXCEPTION;
    private final static QName FRANCIASERVICE_QNAME = new QName("http://codejava.net/", "FranciaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servidor/europa/francia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRANCIASERVICE_WSDL_LOCATION = url;
        FRANCIASERVICE_EXCEPTION = e;
    }

    public FranciaService() {
        super(__getWsdlLocation(), FRANCIASERVICE_QNAME);
    }

    public FranciaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRANCIASERVICE_QNAME, features);
    }

    public FranciaService(URL wsdlLocation) {
        super(wsdlLocation, FRANCIASERVICE_QNAME);
    }

    public FranciaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRANCIASERVICE_QNAME, features);
    }

    public FranciaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FranciaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Francia
     */
    @WebEndpoint(name = "FranciaPort")
    public Francia getFranciaPort() {
        return super.getPort(new QName("http://codejava.net/", "FranciaPort"), Francia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Francia
     */
    @WebEndpoint(name = "FranciaPort")
    public Francia getFranciaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://codejava.net/", "FranciaPort"), Francia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRANCIASERVICE_EXCEPTION!= null) {
            throw FRANCIASERVICE_EXCEPTION;
        }
        return FRANCIASERVICE_WSDL_LOCATION;
    }

}
